CREATE TABLE `creature_guild` (
`guid` INT(10) UNSIGNED NOT NULL ,
`guild` INT(10) UNSIGNED NOT NULL ,
PRIMARY KEY (`guid`)
);

CREATE TABLE `guild_house` (
`guild` INT(10) UNSIGNED NOT NULL ,
`mapId` SMALLINT(5) UNSIGNED NOT NULL ,
`zoneId` SMALLINT(5) UNSIGNED NOT NULL ,
`posX` FLOAT NOT NULL ,
`posY` FLOAT NOT NULL ,
`posZ` FLOAT NOT NULL ,
`gm` VARCHAR(12) NOT NULL ,
`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY (`guild`)
);
